apiVersion: v1
kind: Namespace
metadata:
  name: sayonika
---
apiVersion: v1
kind: Secret
metadata:
  name: sayonika-backend-secrets
data:
  # Please fill this appropriately before deploying this else you're fucked
  recaptcha_checkbox_key: ''
  recaptcha_invisible_key: ''
  virustotal_key: ''
  aes_key: ''
  jwt_secret: ''
  owo_key: ''
  db_pass: ''
  db_user: ''
  db_name: ''
  mail_host: ''
  mail_user: ''
  mail_pass: ''
---
apiVersion: v1
kind: Service
metadata:
 name: sayonika-backend
 namespace: sayonika
spec:
 ports:
 - port: 8000
   name: sayonika-backend
   protocol: TCP
 selector:
   app: sayonika
   tier: backend
 type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
 name: sayonika-backend-services
 namespace: sayonika
spec:
 ports:
 - port: 8082
   name: sayonika-backend-services
   protocol: TCP
 selector:
   app: sayonika
   tier: backend
 type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
 name: sayonika-backend-db
 namespace: sayonika
spec:
 ports:
 - port: 5432
   name: sayonika-backend-db
   protocol: TCP
 selector:
   app: sayonika
   tier: backend
 type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sayonika
    tier: backend
  name: sayonika-backend
  namespace: sayonika
spec:
  selector:
    matchLabels:
      app: sayonika
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: sayonika
        tier: backend
    spec:
      containers:
      - image: postgres:latest
        imagePullPolicy: Always
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
               name: sayonika-backend-secrets
               key: db_name

          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
               name: sayonika-backend-secrets
               key: db_pass

          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
               name: sayonika-backend-secrets
               key: db_user
        volumeMounts:
          - name: backend-db
            mountPath: /var/lib/postgresql/data

        ports:
        - containerPort: 5432
          name: sayonika-backend-db

      volumes:
        - name: backend-db
          hostPath:
              path: /etc/clarity/sayonika/production_data
              type: DirectoryOrCreate

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sayonika
    tier: backend
  name: sayonika-backend
  namespace: sayonika
spec:
  selector:
    matchLabels:
      app: sayonika
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: sayonika
        tier: backend
    spec:
      containers:
      - image: chinodesuuu/sayonika-backend-services:latest
        imagePullPolicy: Always
        name: sayonika-backend
        env:
          - name: SAYONIKA_AV_VIRUSTOTAL_APIKEY
            valueFrom:
              secretKeyRef:
               name: sayonika-backend-secrets
               key: virustotal_key

          - name: SAYONIKA_DB_HOST
            value: postgresql

          - name: SAYONIKA_DB_PORT
            value: 5432

          - name: SAYONIKA_DB_NAME
            valueFrom:
              secretKeyRef:
               name: sayonika-backend-secrets
               key: db_name

          - name: SAYONIKA_DB_PASS
            valueFrom:
              secretKeyRef:
               name: sayonika-backend-secrets
               key: db_pass

          - name: SAYONIKA_DB_USER
            valueFrom:
              secretKeyRef:
               name: sayonika-backend-secrets
               key: db_user
        ports:
        - containerPort: 8082
          name: sayonika-backend-services

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sayonika
    tier: backend
  name: sayonika-backend
  namespace: sayonika
spec:
  selector:
    matchLabels:
      app: sayonika
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: sayonika
        tier: backend
    spec:
      containers:
      - image: chinodesuuu/sayonika-backend:latest
        imagePullPolicy: Always
        name: sayonika-backend
        env:
          - name: SAYONIKA_RECAPTCHA_INVISIBLE_SECRET_KEY
            valueFrom:
              secretKeyRef:
               name: sayonika-backend-secrets
               key: recaptcha_invisible_key

          - name: SAYONIKA_RECAPTCHA_CHECKBOX_SECRET_KEY
            valueFrom:
              secretKeyRef:
               name: sayonika-backend-secrets
               key: recaptcha_checkbox_key

          - name: SAYONIKA_DB_HOST
            value: postgresql

          - name: SAYONIKA_DB_PORT
            value: 5432

          - name: SAYONIKA_DB_NAME
            valueFrom:
              secretKeyRef:
               name: sayonika-backend-secrets
               key: db_name

          - name: SAYONIKA_DB_PASS
            valueFrom:
              secretKeyRef:
               name: sayonika-backend-secrets
               key: db_pass

          - name: SAYONIKA_DB_USER
            valueFrom:
              secretKeyRef:
               name: sayonika-backend-secrets
               key: db_user

          - name: SAYONIKA_OWO_KEY
            valueFrom:
              secretKeyRef:
               name: sayonika-backend-secrets
               key: owo_key

          - name: SAYONIKA_MAIL_SERVER
            valueFrom:
              secretKeyRef:
               name: sayonika-backend-secrets
               key: mail_host

          - name: SAYONIKA_MAIL_USER
            valueFrom:
              secretKeyRef:
               name: sayonika-backend-secrets
               key: mail_user


          - name: SAYONIKA_MAIL_PASSWORD
            valueFrom:
              secretKeyRef:
               name: sayonika-backend-secrets
               key: mail_pass
        
        ports:
        - containerPort: 8000
          name: sayonika-backend
