apiVersion: v1
kind: Namespace
metadata:
  name: sayonika
---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
data:
  # Please fill this appropriately before deploying this else you're fucked
  recaptcha_checkbox_key: ''
  recaptcha_invisible_key: ''
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: sayonika
spec:
  ports:
    - port: 8080
      name: frontend-ext
      protocol: TCP
  selector:
    app: sayonika
    tier: frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sayonika
    tier: frontend
  name: frontend
  namespace: sayonika
spec:
  selector:
    matchLabels:
      app: sayonika
  replicas: 2
  template:
    metadata:
      labels:
        app: sayonika
        tier: frontend
    spec:
      containers:
        - image: sayonika/frontend:beta
          imagePullPolicy: Always
          name: frontend
          env:
            - name: SAYONIKA_RECAPTCHA_INVISIBLE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                name: frontend-secrets
                key: recaptcha_invisible_key
            - name: SAYONIKA_RECAPTCHA_CHECKBOX_SECRET_KEY
              valueFrom:
                secretKeyRef:
                name: frontend-secrets
                key: recaptcha_checkbox_key
            - name: SAYONIKA_API_ORIGIN
              value: http://backend:8000
          ports:
            - containerPort: 8080
              name: frontend-ext
