apiVersion: v1
name: Sayonika
version: 1.0
description: A Highly-available, Planet-scale Mod DB within your Kubernetes cluster.
keywords:
  - mod-db
  - ddlc
  - website
  - vue
  - python
  - postgresql
home: https://github.com/Sayo-nika
sources:
  - https://github.com/Sayo-nika/Frontend
  - https://github.com/Sayo-nika/Backend
maintainers:
  - name: Hikari Kibo
    email: enra@sayonika.moe
    url: https://sayonika.moe

  - name: Michael
    email: iamovyerus@gmail.com
    url: https://ovyerus.me

icon: A URL to an SVG or PNG image to be used as an icon (optional).
appVersion: The version of the app that this contains (optional). This needn't be SemVer.
deprecated: Whether this chart is deprecated (optional, boolean)