dependencies:
  - name: postgresql
    version: 3.10.0
    repository: https://kubernetes-charts.storage.googleapis.com/charts
  - name: elasticsearch
    version: 1.18.1
    repository: https://kubernetes-charts.storage.googleapis.com/charts