# Copyright 2019 (c) Sayonika Project Authors. All Rights Reserved.
# Licensed under MIT. You should have recieved a copy of the license on the project root.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: app-backend
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: app-backend
        tier: backend
    spec:
      containers:
      - name: backend
        image: claritymoe/sayonika-backend:latest
        resources:
          requests:
             cpu: 100m
             memory: 512Mi
        ports:
          - containerPort: 4444