# Copyright 2019 (c) Sayonika Project Authors. All Rights Reserved.
# Licensed under MIT. You should have recieved a copy of the license on the project root.

apiVersion: v1
kind: Service
metadata:
  name: app-backend-internal
  labels:
    app: app-backend
    tier: backend
spec:
  ports:
  - port: 4444
    targetPort: 4444
  selector:
    app: app-backend
    tier: backend